apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: miekclip4-nodejs
  janus-idp.io/tekton: miekclip4-nodejs
  backstage.io/kubernetes-id: miekclip4-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: miekclip4-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
